#!/bin/bash
lock() {
    i3lock
}

case "$1" in
    lock)
        i3lock -i /home/pisceskkk/Pictures/wallpaper/9.jpg
        ;;
    logout)
        i3-msg exit
        ;;
    suspend)
        suspend
        ;;
    hibernate)
        lock && systemctl hibernate
        ;;
    reboot)
        reboot
        ;;
    shutdown)
        poweroff
        ;;
    *)
        echo "Usage: $0 {lock|logout|suspend|hibernate|reboot|shutdown}"
        exit 2
esac

exit 0
