#!/bin/bash
# get all filename in specified path

path=$PWD
files=$(ls $path)
for file in $files
do
    if [ -d $file ]
    then
        cd $file
        github=`git remote -v | sed -n '1p' | cut -f2 | cut -f1 -d " "`
        cd ..
        git submodule add $girhub $PWD/$file
        if [ $? -eq 0 ]
        then
            echo Add $file!
        fi
    fi
done
echo done.
